# Generated by Django 5.1.4 on 2025-01-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passport_or_id',
            field=models.CharField(default=1, max_length=36, unique=True),
            preserve_default=False,
        ),
    ]
